gamesite/enter/urls.py
from django.urls import path
from . import views
from .api.views import teams_detail, entries_detail, my_entries_detail, called_bet_stats, called_bet_position_changes, EntriesViewSet, called_bets, SimpleEntriesViewSet

app_name = "enter"
urlpatterns = [
    path("entrymanager", views.index, name="index"),
    path("leaderboard", views.leaderboard, name="leaderboard"),
    path("results", views.results, name="results"),
    path("explore", views.explore, name="explore"),
    path("entry/<int:entry_id>", views.edit_entry, name="entry"),
    path("entry/new", views.create_entry, name="create_entry"),
    path("entry/random", views.create_random_entry, name="create_random_entry"),
    path("entry/delete/<int:entry_id>", views.delete_entry, name="delete_entry"),
    path("entry/submit/<int:entry_id>", views.submit_entry, name="submit_entry"),
    path("entry/view/<int:entry_id>", views.view_entry, name="view_entry"),
    #     path('api/all', entries_detail, name='all_entries_api'),
    path(
        'api/all', EntriesViewSet.as_view({'get': 'list'}), name='all_entries_api'),
    path(
        'api/submitted-entries', SimpleEntriesViewSet.as_view({'get': 'list'}), name='all_submitted_api'),
    path('api/me', my_entries_detail, name='my_entries_api'),
    path('api/teams', teams_detail, name='teams_api'),
    path('api/called-bets', called_bets, name='called_bets_api'),
    path('api/called-bet-stats/<int:called_bet_id>',
         called_bet_stats, name='bet_success_api'),
    path('api/called-bet-changes/<int:called_bet_id>',
         called_bet_position_changes, name='bet_changes_api'),
]

gamesite/feed/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, PostDeleteView, PostUpdateView, landing, charity, how_it_works, about, entry_guide, entry_guide_italian, how_it_works_italian, glossary, export_csv
from . import views

app_name = "feed"
urlpatterns = [
    path("", landing, name="landing"),
    path("glossario/", glossary, name="glossary"),
    path("entry-guide/", entry_guide, name="entry-guide"),
    path("guida/", entry_guide_italian, name="entry-guide-IT"),
    path("charity/", charity, name="charity"),
    path("how-it-works/", how_it_works, name="how-it-works"),
    path("come-funziona/", how_it_works_italian, name="how-it-works-IT"),
    path("about/", about, name="about"),
    path("export/", export_csv),
    path("home/", PostListView.as_view(), name="home"),
    path("post/<int:pk>/", PostDetailView.as_view(), name="detail"),
    path("post/<int:pk>/update/", PostUpdateView.as_view(), name="update"),
    path("post/<int:pk>/delete/", PostDeleteView.as_view(), name="delete"),
]

gamesite/gamesite/urls.py
import debug_toolbar
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from users.api import views as user_api_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('register/', user_views.register, name='register'),
    path('profile/', include("users.urls")),
    path('settings/edit', user_views.profile_edit, name='profile_edit'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('', include("enter.urls")),
    path('', include("feed.urls")),
    path('all-history-api/',
         user_api_views.AllHistoryViewSet.as_view({'get': 'list'}), name='all_history_api')
]

if settings.DEBUG:
    urlpatterns += [path('__degug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

gamesite/users/urls.py
from django.urls import path
from django.conf.urls import url
from .views import profile, profile_edit
from .api.views import profile_history, profile_performance, winning_positions

# app_name = "users"
urlpatterns = [
    path('<str:username>', profile, name='profile'),
    path('<str:username>/api/history',
         profile_history, name='profile_history_api'),
    path('<str:username>/api/performance',
         profile_performance, name='profile_performance_api'),
    path('prize-api/', winning_positions, name='prize_api'),
    path('edit', profile_edit, name='profile_edit'),
]

gamesite/users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from random import randint
from PIL import Image


def generate_random_code():
    return ''.join([f"{randint(0, 9)}" for _ in range(0, 10)])


class _Image(Image.Image):

    def crop_to_aspect(self, aspect, divisor=1, alignx=0.5, aligny=0.5):
        """Crops an image to a given aspect ratio.
        Args:
            aspect (float): The desired aspect ratio.
            divisor (float): Optional divisor. Allows passing in (w, h) pair as the first two arguments.
            alignx (float): Horizontal crop alignment from 0 (left) to 1 (right)
            aligny (float): Vertical crop alignment from 0 (left) to 1 (right)
        Returns:
            Image: The cropped Image object.
        """
        if self.width / self.height > aspect / divisor:
            newwidth = int(self.height * (aspect / divisor))
            newheight = self.height
        else:
            newwidth = self.width
            newheight = int(self.width / (aspect / divisor))
        img = self.crop((alignx * (self.width - newwidth),
                         aligny * (self.height - newheight),
                         alignx * (self.width - newwidth) + newwidth,
                         aligny * (self.height - newheight) + newheight))
        return img

Image.Image.crop_to_aspect = _Image.crop_to_aspect


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_picture = models.ImageField(
        default='default.jpg', upload_to='profile_pics')
    team = models.ForeignKey(
        'Team', on_delete=models.SET_NULL, blank=True, null=True)
    bio = models.TextField(max_length=160, blank=True, null=True)
    access_code = models.ForeignKey("AccessCode", blank=True, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f"Profile: {self.user.username}"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.profile_picture.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            cropped = img.crop_to_aspect(1)
            cropped.thumbnail(output_size, Image.ANTIALIAS)
            cropped.save(self.profile_picture.path)

    def get_absolute_url(self):
        return reverse('profile', kwargs={'username': self.user.username})


class Team(models.Model):
    name = models.CharField(max_length=30)
    position = models.IntegerField(blank=True, null=True)
    score = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.name}"


class Prize(models.Model):
    TOP = "T"
    MIDDLE = "M"
    BOTTOM = "B"
    BAND_CHOICES = [
        (TOP, "Top"),
        (MIDDLE, "Middle"),
        (BOTTOM, "Bottom")
    ]
    winning_amount = models.DecimalField(max_digits=6, decimal_places=2)
    position = models.IntegerField()
    band = models.CharField(max_length=1, choices=BAND_CHOICES)

    def __str__(self):
        return f"{self.position} ({self.get_band_display()} Prize) : £{self.winning_amount}"


class AccessCode(models.Model):
    code = models.CharField(max_length=10, default=generate_random_code)
    remaining = models.PositiveSmallIntegerField(default=1)

    def __str__(self):
        return f"Code: {self.code} ({self.remaining})"

gamesite/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import RegexValidator
from .models import Profile, AccessCode
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column

from datetime import datetime
from django.conf import settings


class UserRegisterForm(UserCreationForm):
    username = forms.CharField(max_length=8)
    first_name = forms.CharField(max_length=10)
    last_name = forms.CharField(max_length=10)
    email = forms.EmailField()
    access_code = forms.CharField(max_length=10, validators=[
                                  RegexValidator(r'^\d{1,10}$')])

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name',
                  'email', 'password1', 'password2', 'access_code']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['access_code'].help_text = "An access code is required to create an account."
        self.fields['username'].help_text = "A short unique username, 8 characters max."

    def clean_first_name(self, *args, **kwargs):
        first_name = self.cleaned_data.get("first_name")
        return first_name.title()

    def clean_last_name(self, *args, **kwargs):
        last_name = self.cleaned_data.get("last_name")
        return last_name.title()

    def clean_access_code(self, *args, **kwargs):
        access_code = self.cleaned_data.get("access_code")
        # could use a get and try/except block here
        valid_code = AccessCode.objects.filter(code=access_code).first()
        if not valid_code:
            raise forms.ValidationError("This is not a valid access code")
        elif valid_code.remaining <= 0:
            raise forms.ValidationError("This access code has expired")
        return access_code


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()
    username = forms.CharField(max_length=8)
    first_name = forms.CharField(max_length=10)
    last_name = forms.CharField(max_length=10)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.fields['bio'].widget.attrs.update(rows='2', id="bio-text")
        self.fields['team'].help_text = "Want to create you own team? Get in touch, let us know your team name and your team will be created for you and your friends"
        self.fields['bio'].help_text = "160 characters max"
        if datetime.now() > settings.GAME_DEADLINE:
            self.fields['team'].widget.attrs['disabled'] = True

    class Meta:
        model = Profile
        fields = ['profile_picture', 'team', 'bio']

    def clean_team(self):
        instance = getattr(self, 'instance', None)
        if datetime.now() > settings.GAME_DEADLINE:
            return instance.team
        else:
            return self.cleaned_data['team']

gamesite/users/api/views.py
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import generics, status
from rest_framework.viewsets import ReadOnlyModelViewSet
from django.core.cache import cache
from rest_framework import authentication, permissions
from rest_framework.decorators import api_view
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from rest_framework.permissions import IsAuthenticated
from enter import models
from users.models import Profile, Prize
from .serializers import ProfileHistorySerializer, ProfilePerformanceSerializer, \
    PrizeSerializer, ProfilePositionHistorySerializer, EntryPositionHistorySerializer


@api_view(['GET'])
def all_entries_history(request):
    try:
        profiles = Profile.objects.all()
    except Profile.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializer = ProfilePositionHistorySerializer(profiles, many=True)
        return Response(serializer.data)


class AllHistoryViewSet(ReadOnlyModelViewSet):
    queryset = models.Entry.objects.filter(has_submitted=True)
    serializer_class = EntryPositionHistorySerializer

    def list(self, request):
        cache_key = f"all_history_list"

        data = cache.get(cache_key)
        if data:
            return Response(data)

        response = super().list(request)
        cache.set(cache_key, response.data)
        return response


@api_view(['GET'])
def profile_history(request, username):
    try:
        profile = Profile.objects.get(user__username=username)
    except Profile.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializer = ProfileHistorySerializer(profile)
        return Response(serializer.data)


@api_view(['GET'])
def profile_performance(request, username):
    try:
        profile = Profile.objects.get(user__username=username)
    except Profile.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializer = ProfilePerformanceSerializer(profile)
        return Response(serializer.data)


@api_view(['GET'])
def winning_positions(request):
    positions = Prize.objects.all()

    if request.method == 'GET':
        serializer = PrizeSerializer(positions, many=True)
        return Response(serializer.data)

gamesite/users/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from .models import User, AccessCode
from enter import models
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth.decorators import login_required


def register(request):
    if request.method == "POST":
        user_form = UserRegisterForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save()
            new_profile = new_user.profile
            access_code = user_form.cleaned_data.get('access_code')
            access_code_obj = AccessCode.objects.filter(code=access_code).first()
            access_code_obj.remaining -= 1
            access_code_obj.save()
            new_profile.access_code = access_code_obj
            new_profile.save()
            messages.success(request, f"Your account has now been created! You are now able to log in")
            return redirect('login')
    else:
        user_form = UserRegisterForm()
    return render(request, 'users/register.html', {
        'title': "Register",
        'user_form': user_form
    })


@login_required
def profile(request, username):
    user = get_object_or_404(User, username=username)
    entries = user.profile.entries.filter(has_submitted=True)

    return render(request, 'users/profile.html', {
        'title': user.username,
        'user': user,
        'entries': entries,
        'team': user.profile.team,
    })


@login_required
def profile_edit(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f"Your account has been updated")
            return redirect('profile', username=request.user.username)
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    return render(request, 'users/profile_edit.html', {
        'title': f"edit {request.user.username}",
        'u_form': u_form,
        'p_form': p_form
    })

gamesite/users/templates/users/base.html
{% load static %}
{% load svg %}

<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <!-- My CSS -->
  <link href="{% static 'feed/feed.css' %}" rel="stylesheet">

  <!--  Favourite Icon-->
  <link rel="shortcut icon" href="{%  static 'images/favicon.png' %}">

  {% if title %}
  <title>{{ title }} | Football Game | Euro '20</title>
  {% else %}
  <title>Football Game | Euro '20</title>
  {% endif %}
</head>

<body>
  <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top" role="navigation">
      <div class="container-xl" id="site-logo-header">          
        <a class="navbar-brand long-name mr-4" href="{% url 'feed:home' %}">
          {% svg 'football-game-logo' %}
          Football Game | Euro '20</a>
        <a class="navbar-brand short-name mr-4" href="{% url 'feed:home' %}">
          {% svg 'football-game-logo' %}
          Football Game</a>
      </div>
    </nav>
  </header>

  <div class="page container mt-lg">
    {% if messages %}
    {% include 'feed/messages.html' %}
    {% endif %}
    <div class="row justify-content-md-center">
      <div class="col-lg-6 mx-auto">
        <div class="mt-4">
          {% block content %}
          {% endblock content %}
        </div>
      </div>
    </div>
  </div>

  <!-- jQuery and Bootstrap Bundle (includes Popper) -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</body>

</html>

gamesite/users/templates/users/login.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h1>Login</h1>
<div class="card border-light shadow mb-5">
  <div class="card-body">
  <form method="POST">
    {% csrf_token %}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Login to your account</legend>
      {{ form|crispy }}
    </fieldset>
    <div class="form-group">
      <button class="btn btn-outline-primary" type="submit">Login</button>
      <small class="test-muted ml-2">
        <a href="{% url 'password_reset' %}">Forgot Password?</a>
      </small>
    </div>
  </form>
  <div class="border-top pt-3">
    <small class="text-muted">
      Do you need an account? <a class="ml-2" href="{% url 'register' %}">Sign Up Now</a>
    </small>
  </div>
  </div>
</div>
{% endblock content %}

gamesite/users/templates/users/logout.html
{% extends "users/base.html" %}

{% block content %}
<h2>You have been logged out</h2>
<div class="border-top pt-3">
  <p class="text-muted">
    <a href="{% url 'login' %}">Log in again</a>
  </p>
</div>
{% endblock content %}

gamesite/users/templates/users/password_reset.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h1>Login</h1>
<div class="card border-light shadow mb-4">
  <div class="card-body">
  <form method="POST">
    {% csrf_token %}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Reset Password</legend>
      {{ form|crispy }}
    </fieldset>
    <div class="form-group">
      <button class="btn btn-outline-primary" type="submit">Request Password Reset</button>
    </div>
  </form>
  </div>
</div>
{% endblock content %}

gamesite/users/templates/users/password_reset_complete.html
{% extends "users/base.html" %}

{% block content %}
<div class="alert alert-info">
  Your password has been set.
</div>
<a href="{% url 'login' %}">Sign In Here</a>
{% endblock content %}

gamesite/users/templates/users/password_reset_confirm.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h1>Login</h1>
<div class="card border-light shadow mb-4">
  <div class="card-body">
  <form method="POST">
    {% csrf_token %}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Reset Password</legend>
      {{ form|crispy }}
    </fieldset>
    <div class="form-group">
      <button class="btn btn-outline-primary" type="submit">Reset Password</button>
    </div>
  </form>
  </div>
</div>
{% endblock content %}

gamesite/users/templates/users/password_reset_done.html
{% extends "users/base.html" %}

{% block content %}
<div class="alert alert-info">
  An email has been sent with instructions to reset you password
</div>
{% endblock content %}

gamesite/users/templates/users/profile.html
{% extends "users/profile_base.html" %}
{% load static %}
{% load humanize %}
{% load svg %}

{% block button %}
<div class="col-1">
  <a href="{% url 'profile_edit' %}" class="btn btn-outline-secondary btn-sm">Edit</a>
</div>
{% endblock button %}


{% block profile %}

<div class="card border-light shadow mb-4">
  <div class="card-body">
    <h4>Summary</h4>

    <table class="table profile-summary-table">
      <thead>
        <tr>
          <th scope="col"></th>
          {% for entry in entries %}
            {% if entry.label %}
              <th scope="col" style="text-align:center">
                <a href="{% url 'enter:view_entry' entry.id %}">Entry {{ entry.label }}</a>
              </th>
            {% else %}
              {% if request.user == user %}
                <th scope="col" style="text-align:center">
                  <a href="{% url 'enter:view_entry' entry.id %}">My Entry</a>
                </th>
              {% else %}
                <th scope="col" style="text-align:center">
                  <a href="{% url 'enter:view_entry' entry.id %}">{{ user.username }}'s Entry</a>
                </th>
              {% endif %}
            {% endif %}
          {% empty %}
            <th scope="col" style="text-align:center">No Entries</th>
          {% endfor %}
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row">Current Position</th>
          {% for entry in entries %}
            {% if entry.current_position %}
              <td scope="col">{{ entry.current_position|ordinal }}</td>
            {% else %}
              <td scope="col">---</td>
            {% endif %}
          {% empty %}
            <td scope="col">---</td>
          {% endfor %}
        </tr>

        {% if team %}        
        <tr>
          <th scope="row" class="text-muted">Current Position in "{{team}}"</th>
          {% for entry in entries %}
            {% if entry.current_position %}
              <td scope="col" class="text-muted">{{ entry.current_team_position|ordinal }}</td>
            {% else %}
              <td scope="col" class="text-muted">---</td>
            {% endif %}
          {% empty %}
            <td scope="col" class="text-muted">---</td>
          {% endfor %}
        </tr>
        {% endif %}

        <tr>
          <th scope="row">Current Score</th>
          {% for entry in entries %}
            <td scope="col">{{ entry.current_score|intcomma }}</td>
          {% empty %}
            <td scope="col">---</td>
          {% endfor %}
        </tr>
      </tbody>
    </table>
  </div>
</div>

<div class="card border-light shadow mb-4">
  <div class="card-body">

    <h4>History</h4>
    <hr />
    {% if request.user == user %}
    <p class='mb-2'>Your position and score over time</p>
    {% else %}
    <p class='mb-2'>@{{ user.username }}'s position and score over time</p>
    {% endif %}
    <div id="history-charts_container"
      data-entries-url-endpoint="{% url 'profile_history_api' username=user.username %}"
      data-prize-url-endpoint="{% url 'prize_api' %}">
      {% if entries %}
      <div class="row mb-3">
        <div class="col-lg-6">
          <canvas id="positionChartCanvas" width="400" height="400"></canvas>
        </div>
        <div class="col-lg-6">
          <canvas id="scoreChartCanvas" width="400" height="400"></canvas>
        </div>
      </div>
      {% else %}
      <div class="placeholder-box text-muted">No Entries To Display</div>
      {% endif %}
    </div>

    {% if entries %}
    <button type="button" class="btn btn-outline-dark btn-sm" id="xaxis-toggle">Toggle Time Axis</button>
    <small class="mt-3 text-muted">
      {% svg 'info' %}
      Switch between a time axis where called bets are spaced according to the amount of time between them (aka "linear") and a time axis where called bets are equally spaced (aka "series")
    </small>
    {% endif %}

  </div>
</div>

<div class="card border-light shadow mb-4">
  <div class="card-body">
    <h4>Performance</h4>
    <hr />
    {% if request.user == user %}
    <p class='mb-3'>Your performance in each of the game sections (Group Matches, Group Winners etc.)</p>
    {% else %}
    <p class='mb-3'>@{{ user.username }}'s performance in each of the game sections (Group Matches, Group Winners etc.)</p>
    {% endif %}

    <div id="wrapper">
      <div id="performance-chart_container"
        data-entries-url-endpoint="{% url 'profile_performance_api' username=user.username %}">
        {% if entries %}
        <div class="row mt-3 mb-3">
          <div class="col-lg-6 mb-3">
            <canvas id="performanceScoreChart" width="400" height="400"></canvas>
            <small class="mt-3 text-muted">
              {% svg 'info' %}
              Score Performance = (score so far / total possible score so far) %
            </small>
          </div>
          <div class="col-lg-6">
            <canvas id="performanceNumberChart" width="400" height="400"></canvas>
            <small class="mt-3 text-muted">
              {% svg 'info' %}
              Bet Performance = (number of correct bets so far / total bets called so far) %
            </small>
          </div>
        </div>
        {% else %}
        <div class="placeholder-box text-muted">No Entries To Display</div>
        {% endif %}
      </div>
      <div id="middle-element">
      </div>
    </div>


  </div>
</div>

<script type="text/javascript" src="{% static 'users/entrant_performance_chart.js' %}"></script>
<script type="text/javascript" src="{% static 'users/entrant_history_charts.js' %}"></script>


{% endblock profile %}

gamesite/users/templates/users/profile_base.html
{% extends "feed/base.html" %}

{% block content %}
<div class="col-12 mt-4">
<div class="card border-light shadow mb-4">
  <div class="card-body">
    <div class="row no-gutters">
      <div class="col-2">
        <img class="rounded-circle account-img" src="{{ user.profile.profile_picture.url }}">
      </div>
      <div class="col-9">
        <div class="media-body">
          <h2 class="account-heading"><b>{{ user.first_name }} {{ user.last_name }}</b></h2>

          <h3 class="text-muted">@{{ user.username }}</h3>

          {% if user.profile.bio %}
          <p class="text-muted">{{ user.profile.bio }}</p>
          {% else %}
          <p class="mb-4"></p>
          {% endif %}

          <span>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-people-fill" viewBox="0 0 16 16">
              <path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1H7zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
              <path fill-rule="evenodd" d="M5.216 14A2.238 2.238 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.325 6.325 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1h4.216z"/>
              <path d="M4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5z"/>
            </svg>
            {% if user.profile.team %}
            <small class="text-muted">{{ user.profile.team }}</small>
            {% else %}
            <small class="text-muted">---</small>
            {% endif %}
          </span>
        </div>
      </div>
      {% if request.user == user %}
      {% block button %}
      {% endblock button %}
      {% endif %}
    </div>
  </div>
</div>

{% block profile %}
{% endblock profile %}

</div>
{% endblock content %}