gamesite/enter/urls.py
from django.urls import path
from . import views
from .api.views import teams_detail, entries_detail, my_entries_detail, called_bet_stats, called_bet_position_changes, EntriesViewSet, called_bets, SimpleEntriesViewSet

app_name = "enter"
urlpatterns = [
    path("entrymanager", views.index, name="index"),
    path("leaderboard", views.leaderboard, name="leaderboard"),
    path("results", views.results, name="results"),
    path("explore", views.explore, name="explore"),
    path("entry/<int:entry_id>", views.edit_entry, name="entry"),
    path("entry/new", views.create_entry, name="create_entry"),
    path("entry/random", views.create_random_entry, name="create_random_entry"),
    path("entry/delete/<int:entry_id>", views.delete_entry, name="delete_entry"),
    path("entry/submit/<int:entry_id>", views.submit_entry, name="submit_entry"),
    path("entry/view/<int:entry_id>", views.view_entry, name="view_entry"),
    #     path('api/all', entries_detail, name='all_entries_api'),
    path(
        'api/all', EntriesViewSet.as_view({'get': 'list'}), name='all_entries_api'),
    path(
        'api/submitted-entries', SimpleEntriesViewSet.as_view({'get': 'list'}), name='all_submitted_api'),
    path('api/me', my_entries_detail, name='my_entries_api'),
    path('api/teams', teams_detail, name='teams_api'),
    path('api/called-bets', called_bets, name='called_bets_api'),
    path('api/called-bet-stats/<int:called_bet_id>',
         called_bet_stats, name='bet_success_api'),
    path('api/called-bet-changes/<int:called_bet_id>',
         called_bet_position_changes, name='bet_changes_api'),
]

gamesite/feed/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, PostDeleteView, PostUpdateView, landing, charity, how_it_works, about, entry_guide, entry_guide_italian, how_it_works_italian, glossary, export_csv
from . import views

app_name = "feed"
urlpatterns = [
    path("", landing, name="landing"),
    path("glossario/", glossary, name="glossary"),
    path("entry-guide/", entry_guide, name="entry-guide"),
    path("guida/", entry_guide_italian, name="entry-guide-IT"),
    path("charity/", charity, name="charity"),
    path("how-it-works/", how_it_works, name="how-it-works"),
    path("come-funziona/", how_it_works_italian, name="how-it-works-IT"),
    path("about/", about, name="about"),
    path("export/", export_csv),
    path("home/", PostListView.as_view(), name="home"),
    path("post/<int:pk>/", PostDetailView.as_view(), name="detail"),
    path("post/<int:pk>/update/", PostUpdateView.as_view(), name="update"),
    path("post/<int:pk>/delete/", PostDeleteView.as_view(), name="delete"),
]

gamesite/gamesite/urls.py
import debug_toolbar
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from users.api import views as user_api_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('register/', user_views.register, name='register'),
    path('profile/', include("users.urls")),
    path('settings/edit', user_views.profile_edit, name='profile_edit'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('', include("enter.urls")),
    path('', include("feed.urls")),
    path('all-history-api/',
         user_api_views.AllHistoryViewSet.as_view({'get': 'list'}), name='all_history_api')
]

if settings.DEBUG:
    urlpatterns += [path('__degug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

gamesite/feed/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from enter.models import CalledBet
from polymorphic.models import PolymorphicModel
from django.urls import reverse


class Sticker(models.Model):
    name = models.CharField(max_length=100)
    sticker_picture = models.ImageField(upload_to='sticker_pics')

    def __str__(self):
        return f"{self.name}"


class Post(models.Model):
    USER_POST = "U"
    BET_POST = "B"
    TYPE_CHOICES = [
        (USER_POST, "User Post"),
        (BET_POST, "Called Bet Post")
    ]
    title = models.CharField(max_length=100)
    content = models.TextField(blank=True, null=True)
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    is_pinned = models.BooleanField(default=False)
    sticker = models.ForeignKey(
        Sticker, on_delete=models.CASCADE, blank=True, null=True)
    post_type = models.CharField(
        max_length=1, choices=TYPE_CHOICES, blank=True, null=True)
    called_bet = models.OneToOneField(
        CalledBet, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return f'"{self.title}" by {self.author.username}'

    def get_absolute_url(self):
        return reverse('feed:detail', kwargs={'pk': self.pk})

gamesite/feed/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, DetailView, UpdateView, DeleteView
from .models import Post
from django.contrib.auth.decorators import login_required
from users.models import Profile
from django.http import HttpResponse
import csv


def landing(request):
    if request.user.is_authenticated:
        return redirect('feed:home')
    return render(request, 'feed/very-simple-landing.html', {
        'title': "Welcome",
    })


@login_required
def charity(request):
    return render(request, 'feed/charity.html', {
        'title': "Charity",
    })


@login_required
def entry_guide(request):
    return render(request, 'feed/guide.html', {
        'title': "Entry Guide",
    })


@login_required
def entry_guide_italian(request):
    return render(request, 'feed/guide_IT.html', {
        'title': "Come Giocare",
    })


@login_required
def glossary(request):
    return render(request, 'feed/glossary.html', {
        'title': "Glossario",
    })


@login_required
def how_it_works(request):
    return render(request, 'feed/how_it_works.html', {
        'title': "How It Works",
    })


@login_required
def how_it_works_italian(request):
    return render(request, 'feed/how_it_works_IT.html', {
        'title': "Come Funziona",
    })


@login_required
def about(request):
    return render(request, 'feed/about.html', {
        'title': "About",
    })


def export_csv(request):
    if not request.user.is_superuser:
        return redirect('feed:home')

    response = HttpResponse(content_type='text/csv')

    writer = csv.writer(response)
    writer.writerow(['', '', '', '', '', 'Entry A', '', 'Entry B', '', 'Entry C', ''])
    writer.writerow(['First name', 'Last name', 'Username', 'Access Code Used', 'Email Address', 'Created?', 'Submitted?', 'Created?', 'Submitted?', 'Created?', 'Submitted?'])

    for profile in Profile.objects.all():
        first_name = profile.user.first_name
        last_name = profile.user.last_name
        username = profile.user.username
        if profile.access_code:
            access_code = profile.access_code.code
        else: 
            access_code = None
        email_address = profile.user.email
        entry_info = [False] * 6
        for i, entry in enumerate(profile.entries.all()):
            entry_info[i * 2] = True
            entry_info[(i * 2) + 1] = entry.has_submitted
        writer.writerow([first_name, last_name, username, access_code, email_address] + entry_info)

    response['Content-Disposition'] = 'attachment; filename="export.csv"'

    return response


class PostListView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'feed/home.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 10

    def get_context_data(self, *args, **kwargs):
        context = super(PostListView,self).get_context_data(*args, **kwargs)
        context['pinned_post'] = Post.objects.order_by('-date_posted').filter(is_pinned=True).first()
        return context


class PostDetailView(LoginRequiredMixin, DetailView):
    model = Post


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

gamesite/feed/templates/feed/about.html
{% extends "feed/base.html" %}
{% load humanize %}

{% block content %}

{% include 'feed/profile_sidebar.html'%}

<div class="col-12 col-lg-9 mt-4">
  <h2>About</h2>
  <div class="card border-light shadow mb-4">
    <div class="card-body">
      <h3>Lessons Learnt From Past Competitions</h3>
      <ul>
        <li>So called football experts rarely win this competition</li>
        <li>The game is skewed towards the final. This allows for a great ending as most people may still be able to win</li>
        <li>The older you become and the more football you watch, the less you really know about the game</li>
        <li>For those who are not married, get married and let your partner do your entry</li>
        <li>Have another child and let your one year old make the selections</li>
        <li>Watch less football</li>
        <li>Do not laugh at your partner or child. After they have completed their entry, copy some of their selections when they are not looking</li>
        <li>Do not laugh when someone picks a team based on looks or on their favourite colour</li>
        <li>Do not tease your partner or child saying they do not know anything about football because they tend to beat you</li>
      </ul>
    </div>
  </div>

</div>

{% endblock content %}

gamesite/feed/templates/feed/base.html
{% load static %}
{% load humanize %}
{% load svg %}

<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
    integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
  <!-- My CSS -->
  <link href="{% static 'feed/feed.css' %}" rel="stylesheet">

  <!--  Favourite Icon-->
  <link rel="shortcut icon" href="{%  static 'images/favicon.png' %}">

  {% if title %}
  <title>{{ title }} | Football Game | Euro '20</title>
  {% else %}
  <title>Football Game | Euro '20</title>
  {% endif %}
</head>

<body>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <!-- jQuery and Bootstrap Bundle (includes Popper) -->

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.0.1/chart.min.js"
    integrity="sha512-2uu1jrAmW1A+SMwih5DAPqzFS2PI+OPw79OVLS4NJ6jGHQ/GmIVDDlWwz4KLO8DnoUmYdU8hTtFcp8je6zxbCg=="
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"
    integrity="sha512-qTXRIMyZIFb8iQcfjXWCO8+M5Tbc38Qi5WzdPOYZHIlZpzBHG3L3by84BBBOiRGiEb7KKtAOAs5qYdUiZiQNNQ=="
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-moment@1.0.0/dist/chartjs-adapter-moment.min.js"></script>

  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.23/r-2.2.7/datatables.min.css" />
  <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.23/r-2.2.7/datatables.min.js"></script>
  <script type="text/javascript" charset="utf-8"  src="https://cdn.datatables.net/plug-ins/1.10.24/sorting/datetime-moment.js"></script>
  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/progressbar.js/1.0.0/progressbar.min.js"
    integrity="sha512-Hivnqo7w/SRPjJY3qvD8Y1CaKbmrmqDjZKYgIFyIag/2bOye6Qk1W99wZYObixwzYoZQeKWPqZ2ifus82GE07A=="
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-circle-progress/1.2.2/circle-progress.min.js"
    integrity="sha512-6kvhZ/39gRVLmoM/6JxbbJVTYzL/gnbDVsHACLx/31IREU4l3sI7yeO0d4gw8xU5Mpmm/17LMaDHOCf+TvuC2Q=="
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"
    integrity="sha512-0QbL0ph8Tc8g5bLhfVzSqxe9GERORsKhIn1IrpxDAgUsbBGz/V7iSav2zzW325XGd1OMLdL4UiqRJj702IeqnQ=="
    crossorigin="anonymous"></script>

  <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top" role="navigation">
      <div class="container-xl" id="site-logo-header">
        <a class="navbar-brand long-name mr-4" href="{% url 'feed:home' %}">
          {% svg 'football-game-logo' %}
          Football Game | Euro '20</a>
        <a class="navbar-brand short-name mr-4" href="{% url 'feed:home' %}">
          {% svg 'football-game-logo' %}
          Football Game</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
          aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-item nav-link" href="{% url 'feed:home' %}" id="home-navbar-link">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-item nav-link" href="{% url 'enter:index' %}" id="enter-navbar-link">Enter</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="exploreDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                Explore
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'enter:leaderboard' %}">Leaderboards</a>
                <a class="dropdown-item" href="{% url 'enter:results' %}">Results</a>
                <a class="dropdown-item" href="{% url 'enter:explore' %}">Charts</a>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="infoDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                Info
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'feed:how-it-works' %}">How It Works</a>
                <a class="dropdown-item" href="{% url 'feed:entry-guide' %}">Entry Guide</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'feed:how-it-works-IT' %}">Come Funziona</a>
                <a class="dropdown-item" href="{% url 'feed:entry-guide-IT' %}">Come Giocare</a>
                <a class="dropdown-item" href="{% url 'feed:glossary' %}">Glossario</a>
              </div>
            </li>
          </ul>
          <!-- Navbar Right Side -->
          <ul class="navbar-nav">
            {% if user.is_authenticated %}
            {% comment %} {% if user.is_superuser %}
            <li class="nav-item">
              <a class="nav-item nav-link" href="{% url 'admin:index' %}" id="home-navbar-link">Admin</a>
            </li>
            {% endif %} {% endcomment %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <img class="rounded-circle account-img-sm" src="{{ request.user.profile.profile_picture.url }}">
              </a>
              <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="{% url 'profile' username=request.user.username %}">My Profile</a></li>
                <li>
                  <div class="dropdown-divider"></div>
                </li>
                <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
              </ul>
            </li>
            {% else %}
            <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
            <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
  </header>

  <div class="page container mt-lg">
    {% if messages %}
    {% include 'feed/messages.html' %}
    {% endif %}
    <div class="row">
      {% block content %}
      {% endblock content %}
    </div>
  </div>


  <div class="footer-dark mt-5">
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-md-6 item">
            <h3>Contact Us</h3>
            <ul>
              <li><a href="mailto:dansarno91@gmail.com">Daniel</a> - website questions, feedback or help</li>
              <li><a href="mailto:euro2020@ros.co.uk">Ros</a> - game questions, rules, charity contribution</li>
              <li><a href="mailto:euro2020@blu.it">Erminio</a> - italian translation, game questions and rules</li>
            </ul>
          </div>
          <div class="col-md-6 item text">
            <h3>Football Game</h3>
            <p>Private pools game for friends and family. The game has evolved since it's origins in the 90's, with this year's installment being online for the first time, following Euro 2020 and raising money for charity along the way.</p>
          </div>
        </div>
        <p class="copyright">Football Game © 2021</p>
      </div>
    </footer>
  </div>

  <script>
    const $dropdown = $(".dropdown");
    const $dropdownToggle = $(".dropdown-toggle");
    const $dropdownMenu = $(".dropdown-menu");
    const showClass = "show";
    
    $(window).on("load resize", function() {
      if (this.matchMedia("(min-width: 768px)").matches) {
        $dropdown.hover(
          function() {
            const $this = $(this);
            $this.addClass(showClass);
            $this.find($dropdownToggle).attr("aria-expanded", "true");
            $this.find($dropdownMenu).addClass(showClass);
          },
          function() {
            const $this = $(this);
            $this.removeClass(showClass);
            $this.find($dropdownToggle).attr("aria-expanded", "false");
            $this.find($dropdownMenu).removeClass(showClass);
          }
        );
      } else {
        $dropdown.off("mouseenter mouseleave");
      }
    });
  </script>

</body>

</html>

gamesite/feed/templates/feed/home.html
{% extends "feed/base.html" %}
{% load humanize %}
{% load svg %}

{% block content %}

{% include 'feed/profile_sidebar.html'%}

<div class="col-12 col-lg-9 mt-4">
  
  <h2>Feed</h2>

  {% comment %} <div class="card text-center mb-4">
    <div class="card-body">
      <h5 class="card-title">Ready to Create Your Game Entry?</h5>
      <p class="card-text">Click this link below to be taken to the Entry Manager where you can create, edit and submit entries.</p>
      <a href="{% url 'enter:index' %}" class="btn btn-primary">Let's begin</a>
    </div>
  </div> {% endcomment %}
  
  {% if pinned_post %}
  <div class="card border-secondary shadow mb-4">
    <div class="card-body">
      <div class="media">
        <a class="mr-2" href="{% url 'profile' username=pinned_post.author.username %}">
          <img class="rounded-circle article-img" src="{{pinned_post.author.profile.profile_picture.url }}">
        </a>
        <div class="media-body">
          <div class="article-metadata">
            <a class="mr-2" href="{% url 'profile' username=pinned_post.author.username %}">{{ pinned_post.author }}</a>
            <small class="text-muted">{{ pinned_post.date_posted|naturaltime }}</small>
            {% svg 'bookmark_icon' %}
          </div>
          <h3><a class="article-title" href="{% url 'feed:detail' pinned_post.id %}">{{ pinned_post.title }}</a></h3>
          <p class="article-content">{{ pinned_post.content|truncatewords_html:50|safe }}</p>
        </div>
      </div>
    </div>
    {% if pinned_post.sticker %}
    <img class="sticker-img" src="{{pinned_post.sticker.sticker_picture.url }}">
    {% endif %}
  </div>
  {% endif %}

  {% for post in posts %}

  {% if not post.is_pinned %}
  <div class="card border-light shadow mb-4">
    <div class="card-body">
      <div class="media">
        <a class="mr-2" href="{% url 'profile' username=post.author.username %}">
          <img class="rounded-circle article-img" src="{{post.author.profile.profile_picture.url }}">
        </a>
        <div class="media-body">
          <div class="article-metadata">
            <a class="mr-2" href="{% url 'profile' username=post.author.username %}">{{ post.author }}</a>
            <small class="text-muted">{{ post.date_posted|naturaltime }}</small>
          </div>
          <h3><a class="article-title" href="{% url 'feed:detail' post.id %}">{{ post.title }}</a></h3>
          <p class="article-content">{{ post.content|truncatewords_html:50|safe }}</p>
        </div>
      </div>
    </div>
    {% if post.sticker %}
    <img class="sticker-img" src="{{post.sticker.sticker_picture.url }}">
    {% endif %}
  </div>
  {% endif %}

  {% empty %}
  <div class="card text-center border-light shadow-sm mb-4">
    <div class="card-body">
      <h5>No posts yet, watch this space...</h5>
    </div>
  </div>
  {% endfor %}

  <!--Pagination-->
  {% if is_paginated %}
  <nav class="mb-3">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Latest</a></li>
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Next</a></li>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
      {% if page_obj.number == num %}
      <li class="page-item active"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
      {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
      <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
      {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Previous</a></li>
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">First</a></li>
      {% endif %}
    </ul>
  </nav>
  {% endif %}
  <!--end of Pagination-->

</div>

<script>
  $(document).ready(function () {
    $('#home-navbar-link').addClass('active');
  });
</script>

{% endblock content %}

gamesite/feed/templates/feed/messages.html
<div class="mt-3">
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}
</div>

gamesite/feed/templates/feed/post_detail.html
{% extends "feed/base.html" %}
{% load static %}
{% load humanize %}

{% block content %}

{% include 'feed/profile_sidebar.html'%}

<div class="col-12 col-lg-9 mt-4">
  <h2>Post Detail</h2>
  <div class="card border-light shadow mb-3">
    <div class="card-body">
      <div class="media d-block d-md-flex">
        <a class="mr-2" href="{% url 'profile' username=post.author.username %}">
          <img class="rounded-circle article-img" src="{{post.author.profile.profile_picture.url }}">
        </a>
        <div class="media-body">
          <div class="article-metadata">
            <a class="mr-2" href="{% url 'profile' username=post.author.username %}">{{ post.author }}</a>
            <small class="text-muted">{{ post.date_posted|naturaltime }}</small>
          </div>
          <h3>{{ post.title }}</h3>
          <p class="article-content">{{ post.content|safe }}</p>
        </div>
      </div>
    </div>
  </div>

  {% if post.post_type == 'B' %}
  <div class="card border-light shadow mb-5">
    <div class="card-body">
      <h2>More Call Info</h2>
      <hr>

      <div class="row">
        <div class="col-md-6">
          <div id="table_container" class="container-fluid"
            data-url-endpoint="{% url 'enter:bet_changes_api' called_bet_id=post.called_bet.id %}">
            <h5>Biggest Winners</h5>
            <table id="winners-leaderboard" class="display" style="width:100%; td, th {font-size: x-small;}">
              <thead>
                <tr>
                  <th class="all"></th>
                  <th>From</th>
                  <th>To</th>
                  <th>ΔPos</th>
                </tr>
              </thead>
            </table>

            <hr>

            <h5>Biggest Losers</h5>
            <table id="losers-leaderboard" class="display" style="width:100%">
              <thead>
                <tr>
                  <th class="all"></th>
                  <th>From</th>
                  <th>To</th>
                  <th>ΔPos</th>
                </tr>
              </thead>
            </table>
          </div>

        </div>

        <div class="col-md-6">
          <div id="bet-success-chart_container" class="mt-5"
            data-bet-success-url-endpoint="{% url 'enter:bet_success_api' called_bet_id=post.called_bet.id %}">
            <canvas id="betSuccessChart" width="400" height="400"></canvas>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endif %}
</div>

{% if post.post_type == 'B' %}
<script type="text/javascript" src="{% static 'feed/bet_success_chart.js' %}"></script>
<script type="text/javascript" src="{% static 'feed/bet_winners_and_losers_leaderboard.js' %}"></script>
{% endif %}


{% endblock content %}