gamesite/enter/urls.py
from django.urls import path
from . import views
from .api.views import teams_detail, entries_detail, my_entries_detail, called_bet_stats, called_bet_position_changes, EntriesViewSet, called_bets, SimpleEntriesViewSet

app_name = "enter"
urlpatterns = [
    path("entrymanager", views.index, name="index"),
    path("leaderboard", views.leaderboard, name="leaderboard"),
    path("results", views.results, name="results"),
    path("explore", views.explore, name="explore"),
    path("entry/<int:entry_id>", views.edit_entry, name="entry"),
    path("entry/new", views.create_entry, name="create_entry"),
    path("entry/random", views.create_random_entry, name="create_random_entry"),
    path("entry/delete/<int:entry_id>", views.delete_entry, name="delete_entry"),
    path("entry/submit/<int:entry_id>", views.submit_entry, name="submit_entry"),
    path("entry/view/<int:entry_id>", views.view_entry, name="view_entry"),
    #     path('api/all', entries_detail, name='all_entries_api'),
    path(
        'api/all', EntriesViewSet.as_view({'get': 'list'}), name='all_entries_api'),
    path(
        'api/submitted-entries', SimpleEntriesViewSet.as_view({'get': 'list'}), name='all_submitted_api'),
    path('api/me', my_entries_detail, name='my_entries_api'),
    path('api/teams', teams_detail, name='teams_api'),
    path('api/called-bets', called_bets, name='called_bets_api'),
    path('api/called-bet-stats/<int:called_bet_id>',
         called_bet_stats, name='bet_success_api'),
    path('api/called-bet-changes/<int:called_bet_id>',
         called_bet_position_changes, name='bet_changes_api'),
]

gamesite/feed/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, PostDeleteView, PostUpdateView, landing, charity, how_it_works, about, entry_guide, entry_guide_italian, how_it_works_italian, glossary, export_csv
from . import views

app_name = "feed"
urlpatterns = [
    path("", landing, name="landing"),
    path("glossario/", glossary, name="glossary"),
    path("entry-guide/", entry_guide, name="entry-guide"),
    path("guida/", entry_guide_italian, name="entry-guide-IT"),
    path("charity/", charity, name="charity"),
    path("how-it-works/", how_it_works, name="how-it-works"),
    path("come-funziona/", how_it_works_italian, name="how-it-works-IT"),
    path("about/", about, name="about"),
    path("export/", export_csv),
    path("home/", PostListView.as_view(), name="home"),
    path("post/<int:pk>/", PostDetailView.as_view(), name="detail"),
    path("post/<int:pk>/update/", PostUpdateView.as_view(), name="update"),
    path("post/<int:pk>/delete/", PostDeleteView.as_view(), name="delete"),
]

gamesite/gamesite/urls.py
import debug_toolbar
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from users.api import views as user_api_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('register/', user_views.register, name='register'),
    path('profile/', include("users.urls")),
    path('settings/edit', user_views.profile_edit, name='profile_edit'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('', include("enter.urls")),
    path('', include("feed.urls")),
    path('all-history-api/',
         user_api_views.AllHistoryViewSet.as_view({'get': 'list'}), name='all_history_api')
]

if settings.DEBUG:
    urlpatterns += [path('__degug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

gamesite/enter/api/views.py
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.viewsets import ReadOnlyModelViewSet
from django.core.cache import cache
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from rest_framework import generics, status
from rest_framework import authentication, permissions
from rest_framework.decorators import api_view
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from rest_framework.permissions import IsAuthenticated
from enter import models
from users.models import Team
from .serializers import LeaderboardEntrySerializer, SidebarEntrySerializer, CalledBetStatsSerializer, CalledBetWinnersAndLosersSerializer, TeamSerializer, CalledBetSerializer, SimpleEntrySerializer
from django.conf import settings
from datetime import datetime


@api_view(['GET'])
def teams_detail(request):
    try:
        teams = Team.objects.all()
    except Team.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializer = TeamSerializer(teams, many=True)
        return Response(serializer.data)


class EntriesViewSet(ReadOnlyModelViewSet):
    queryset = models.Entry.objects.filter(has_submitted=True)
    serializer_class = LeaderboardEntrySerializer

    # @method_decorator(cache_page(60*60*2))
    # def list(self, request, *args, **kwargs):
    #     return super().list(request, *args, **kwargs)

    def list(self, request):
        cache_key = "entries_list"

        data = cache.get(cache_key)
        # if cached data exists and the game has started, use the cached data
        if data:  # and datetime.now() > settings.GAME_DEADLINE:
            return Response(data)

        response = super().list(request)
        cache.set(cache_key, response.data)
        return response


class SimpleEntriesViewSet(ReadOnlyModelViewSet):
    queryset = models.Entry.objects.filter(has_submitted=True)
    serializer_class = SimpleEntrySerializer


@api_view(['GET'])
def entries_detail(request):
    try:
        entries = models.Entry.objects.filter(has_submitted=True)
    except models.Entry.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializer = LeaderboardEntrySerializer(entries, many=True)
        return Response(serializer.data)


@api_view(['GET'])
def my_entries_detail(request):
    try:
        my_entries = models.Entry.objects.filter(
            profile=request.user.profile, has_submitted=True)
    except models.Entry.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializer = SidebarEntrySerializer(my_entries, many=True)
        return Response(serializer.data)


@api_view(['GET'])
def called_bets(request):
    try:
        called_bets = models.CalledBet.objects.all().order_by('date')
    except models.CalledBet.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializer = CalledBetSerializer(called_bets, many=True)
        return Response(serializer.data)


@api_view(['GET'])
def called_bet_stats(request, called_bet_id):
    try:
        stats = models.CalledBetStats.objects.get(called_bet__id=called_bet_id)
    except models.CalledBetStats.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializer = CalledBetStatsSerializer(stats)
        return Response(serializer.data)


@api_view(['GET'])
def called_bet_position_changes(request, called_bet_id):
    try:
        called_bet = models.CalledBet.objects.get(id=called_bet_id)
    except models.CalledBet.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializer = CalledBetWinnersAndLosersSerializer(called_bet)
        return Response(serializer.data)

gamesite/enter/templates/enter/all_history.html
{% extends "feed/base.html" %}
{% load static %}
{% load humanize %}
{% load svg %}

{% block content %}

{% include 'feed/profile_sidebar.html'%}

<div class="col-12 col-lg-9 mt-4">
<h2>Position Charts</h2>

  <div id="all-history-chart-container" data-all-history-url-endpoint="{% url 'all_history_api' %}" data-prize-url-endpoint="{% url 'prize_api' %}" data-username="{{ request.user.username }}" data-called-bets-url-endpoint="{% url 'enter:called_bets_api' %}">
    <div class="card border-light shadow mb-4">
      <div class="card-body">
        <h3>Entries In Winning Positions</h3>
        <p>The position history of entries that are currently in winning positions.</p>
          <hr />
        <div class="d-flex justify-content-center">
          <div class="spinner-border text-secondary loading mt-5" role="status">
            <span class="sr-only">Loading...</span>
          </div>
        </div>
        <div>
          <canvas id="winnersChart" height="600"></canvas>
        </div>
        <button type="button" class="btn btn-outline-dark btn-sm" id="xaxis-toggle" style="display:none">Toggle Time Axis</button>
        <small class="mt-3 text-muted">
          {% svg 'info' %}
          Switch between a time axis where called bets are spaced according to the amount of time between them (aka "linear") and a time axis where called bets are equally spaced (aka "series")
        </small>
      </div>
    </div>
  </div>

  <div class="card border-light shadow mb-4">
      <div class="card-body">
        <h3>Top 20</h3>
        <p>The position history of entries that are currently in the top 20 positions.</p>
          <hr />
        <div class="d-flex justify-content-center">
          <div class="spinner-border text-secondary loading mt-5" role="status">
            <span class="sr-only">Loading...</span>
          </div>
        </div>
        <div>
          <canvas id="top20Chart" height="600"></canvas>
        </div>
        <button type="button" class="btn btn-outline-dark btn-sm" id="xaxis-toggle2" style="display:none">Toggle Time Axis</button>
        <small class="mt-3 text-muted">
          {% svg 'info' %}
          Switch between a time axis where called bets are spaced according to the amount of time between them (aka "linear") and a time axis where called bets are equally spaced (aka "series")
        </small>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript" src="{% static 'users/all_history_chart.js' %}"></script>

<script>
  $(document).ready(function () {
    $('#exploreDropdown').addClass('active');
  });
</script>

{% endblock content %}

gamesite/enter/templates/enter/confirm.html
{% extends "feed/base.html" %}

{% block content %}
<h1>Review and Confirm Submission</h1>
<text>Summary of choices</text>
<form>
  {% for submission in submission %}
  {{ submission }}
  {% endfor %}
  <input type="submit" class="btn btn-primary btn-lg">
</form>
<a href="{% url 'enter:entry' %}">Back to submission</a>
{% endblock content %}

gamesite/enter/templates/enter/enter_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <!-- My CSS -->
  <link href="{% static 'enter/styles.css' %}" rel="stylesheet">

  <!--  Favourite Icon-->
  <link rel="shortcut icon" href="{%  static 'images/favicon.png' %}">

  {% if title %}
  <title>{{ title }} | Football Game | Euro '20</title>
  {% else %}
  <title>Football Game | Euro '20</title>
  {% endif %}
</head>

<body>
    <!-- jQuery and Bootstrap Bundle (includes Popper) -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous">
  </script>
  
  <div class="card entry-card border-light shadow">
    {% block content %}
    {% endblock content %}
  </div>

</body>

</html>

gamesite/enter/templates/enter/entry.html
{% extends "enter/enter_base.html" %}
{% load static %}
{% load svg %}

{% block content %}
<div class="entry-header">
  <h1 class="text-center mt-4">{% svg 'football-game-logo' %}
  <b>Football Game | Euro '20</b></h1>
  <h2 class="text-center mb-4">Entry Form</h2>
</div>
<div class="entry-body">
  <form method="POST" id="entry-form">
    <div class="btn-group" role="group" id="btn-group-1">
      <a href="{% url 'enter:index' %}" class="btn btn-secondary btn-sm return-btn mr-1" id="return-btn-1">Back</a>
      <button type="submit" class="btn btn-primary btn-sm" value="Save">Save</button>
    </div>
    {% csrf_token %}
    {% include 'enter/form.html' %}
    <div class="btn-group" role="group" id="btn-group-2">
      <a href="{% url 'enter:index' %}" class="btn btn-secondary btn-sm return-btn mr-1" id="return-btn-1">Back</a>
      <button type="submit" class="btn btn-primary btn-sm" value="Save">Save</button>
    </div>
  </form>
</div>

<script type="text/javascript" src="{% static 'enter/randomise.js' %}"></script>

<script>
  $(document).ready(function () {
    $("body").tooltip({
      selector: '[data-toggle=tooltip]'
    });
  });
</script>

{% endblock content %}

gamesite/enter/templates/enter/group_matches.html
{% extends "enter/index.html" %}

{% block group_matches %}



{% endblock group_matches %}

gamesite/enter/templates/enter/index.html
{% extends "feed/base.html" %}
{% load humanize %}
{% load svg %}

{% block content %}

{% include 'feed/profile_sidebar.html'%}

<div class="col-12 col-lg-9 mt-4">
  <h2>Entry Manager</h2>
  <div class="card border-light shadow mb-4">
    <div class="card-body">
      <div class="pb-4">You can submit up to 3 entries per person. Each entry costs £8.50 and must be submitted by 23:59 10th June.
      </div>
      <div class="mb-4 text-muted">
      E' possibile compilare fino a 3 schede a persona. Ogni scheda ha un costo di 10 Euro e deve essere inviato entro le 23:59 del 10 Giugno.
      </div>
      <div class="row row-cols-1 row-cols-md-3">
        {% for entry_and_progress in entries_and_progress %}
        <div class="col mb-4">
          {% if has_deadline_passed and not entry_and_progress.entry.has_submitted %}
          <div class="card h-100 muted-card">
          {% else %}
          <div class="card h-100">
          {% endif %}
            {% if entry_and_progress.entry.label %}
            <div class="card-header hex-labeled-entry">
              <h3 class="mr-2">Entry</h3>
              {% if entry_and_progress.entry.label == 'A' %}
              {% svg 'A-label' %}
              {% elif entry_and_progress.entry.label == 'B' %}
              {% svg 'B-label' %}
              {% elif entry_and_progress.entry.label == 'C' %}
              {% svg 'C-label' %}
              {% endif %}
            </div>
            {% else %}
            <div class="card-header">
              <h3>My Entry</h3>
            </div>
            {% endif %}
            <div class="card-body">
              <div class="card-text mb-1">Complete: {{ entry_and_progress.progress }}%</div>
              <div class="progress mb-2" style="height: 5px;">
                <div class="progress-bar bg-primary" role="progressbar"
                  style="width: {{ entry_and_progress.progress }}%" aria-valuenow="{{ entry_and_progress.progress }}"
                  aria-valuemin="0" aria-valuemax="100"></div>
              </div>
              <div class="card-text mb-4">Submitted: {{ entry_and_progress.entry.has_submitted|yesno:"Yes,No" }}</div>
              {% if entry_and_progress.entry.has_submitted %}
              <a href="{% url 'enter:view_entry' entry_and_progress.entry.id %}"
                class="btn btn-outline-secondary btn-sm mr-1">View</a>
              {% else %}
              {% if entry_and_progress.progress == 100 and not has_deadline_passed %}
              <button type="button" class="btn btn-outline-primary btn-sm mr-1 mb-2" data-toggle="modal"
                data-target="#submitModalForEntry{{ entry_and_progress.entry.id }}">
                Submit
              </button>
              {% else %}
              <span class="d-inline-block" tabindex="0" data-toggle="tooltip" data-placement="bottom" title="You can only submit fully complete entries">
              <button type="button" class="btn btn-outline-primary btn-sm mr-1 mb-2" style="pointer-events: none;" disabled>
                Submit
              </button>
              </span>
              {% endif %}
              {% if not has_deadline_passed %}
              <a href="{% url 'enter:entry' entry_and_progress.entry.id %}"
                class="btn btn-outline-secondary btn-sm mr-1 mb-2">Edit</a>
              <button type="button" class="btn btn-outline-danger btn-sm mb-2" data-toggle="modal"
                data-target="#deleteModalForEntry{{ entry_and_progress.entry.id }}">
                Delete
              </button>
              {% else %}
              <a href="{% url 'enter:entry' entry_and_progress.entry.id %}"
                class="btn btn-outline-secondary btn-sm mr-1 mb-2 disabled">Edit</a>
              <button type="button" class="btn btn-outline-danger btn-sm mb-2" data-toggle="modal"
                data-target="#deleteModalForEntry{{ entry_and_progress.entry.id }}" disabled>
                Delete
              </button>
              {% endif %}
              {% endif %}
            </div>
            <div class="card-footer">
              {% if entry_and_progress.entry.date_submitted %}
              <small class="text-muted">Submitted on: {{ entry_and_progress.entry.date_submitted|date:"D d M Y" }}</small>
              {% else %}
              <small class="text-muted">Updated: {{ entry_and_progress.entry.date_updated|naturaltime }}</small>
              {% endif %}
            </div>
          </div>
        </div>

        <!-- Submit Entry Modal -->
        <div class="modal fade" id="submitModalForEntry{{ entry_and_progress.entry.id }}" tabindex="-1" role="dialog"
          aria-labelledby="submitModalCenterTitle" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="submitModalLabel">Submit Entry Confirmation</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                Are you sure you want to submit this entry? This action cannot be undone.
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">No, Take Me Back</button>
                <a href="{% url 'enter:submit_entry' entry_and_progress.entry.id %}" class="btn btn-primary">Confirm
                  Submission</a>
              </div>
            </div>
          </div>
        </div>

        <!-- Delete Entry Modal -->
        <div class="modal fade" id="deleteModalForEntry{{ entry_and_progress.entry.id }}" tabindex="-1" role="dialog"
          aria-labelledby="deleteModalCenterTitle" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Entry Confirmation</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                Are you sure you want to permanently delete this entry? This action cannot be undone.
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">No, Take Me Back</button>
                <a href="{% url 'enter:delete_entry' entry_and_progress.entry.id %}" class="btn btn-danger">Confirm
                  Deletion</a>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}

        {% if num_of_entries < 3 and not has_deadline_passed %}
        <div class="col mb-4">
          <div class="card new-entry-card h-100">
            <div class="card-body">
            <a href="{% url 'enter:create_entry' %}" class="btn btn-outline-primary">+ New Entry</a>
            <h5>or</h5>
            <a href="{% url 'enter:create_random_entry' %}" class="btn btn-outline-primary">+ Random Entry</a>
            </div>
          </div>
        </div>
        {% endif %}

      </div>
    </div>
  </div>

  {% comment %} <div class="card border-light shadow">
    <div class="card-body">
      <h5>Game Rules Summary</h5>
      <ol>
        <li>Each entry costs £8.50 and must be paid by 11th June 2021</li>
        <li>Entries must be submitted in order to enter the game</li>
        <li></li>
      </ol>
    </div>
  </div> {% endcomment %}
</div>

<script>
  $(document).ready(function () {
    $('#enter-navbar-link').addClass('active');
  });
</script>

{% endblock content %}

gamesite/enter/templates/enter/leader_board.html
{% extends "feed/base.html" %}
{% load static %}
{% load humanize %}

{% block content %}

<div class="col-lg-12 mt-4">
  <h2>Leaderboards</h2>

  <div class="card border-light shadow mb-5">
    <div class="card-body">
      <div id="overall_table_container" data-any-called-bets="{{ any_called_bets }}" data-entries-info-url-endpoint="{% url 'enter:all_submitted_api' %}" data-url-endpoint="{% url 'enter:all_entries_api' %}" data-teams-url-endpoint="{% url 'enter:teams_api' %}" data-prizes-url-endpoint="{% url 'prize_api' %}">
        <h3>Overall Leaderboard</h3>
        <hr />
        {% if any_called_bets %}
        <table id="overall_leaderboard" class="display" style="width:100%">
          <thead>
            <tr>
              <th>Pos</th>
              <th class="all"></th>
              <th>User</th>
              <th>Name</th>
              <th data-toggle="tooltip" data-placement="bottom" title="Last 5 results">Form</th>
              <th class="correct-bets-header">Correct Outcomes</th>
              <th>Score</th>
            </tr>
          </thead>
        </table>
        {% else %}
        <table id="all_submitted_entries_table" class="display" style="width:100%">
          <thead>
            <tr>
              <th class="all"></th>
              <th>User</th>
              <th>Name</th>
            </tr>
          </thead>
        </table>
        {% endif %}
      </div>
    </div>
  </div>

  <h2 class="mb-3">Team Leaderboards</h2>

  {% if any_called_bets %}
  <div class="card border-light shadow mb-4">
    <div class="card-body">
      <div id="team_comparison_table_container" class="mb-4">
        <h3>Team Leaderboard</h3>
        <hr />
        <table id="teams_leaderboard" class="display" style="width:100%">
          <thead>
            <tr>
              <th>Pos</th>
              <th>Team</th>
              <th>Average Score</th>
            </tr>
          </thead>
        </table>
      </div>
    </div>
  </div>
  {% endif %}

  {% for team in teams %}
  <div class="card border-light shadow mb-4">
    <div class="card-body">
      <div id="team_{{ team.id }}_table_container" class="mb-4">
        <h3>{{ team }} Leaderboard</h3>
        <hr />
        {% if any_called_bets %}
        <table id="team_{{ team.id }}_leaderboard" class="display" style="width:100%">
          <thead>
            <tr>
              <th>Pos</th>
              <th class="all"></th>
              <th>User</th>
              <th>Name</th>
              <th data-toggle="tooltip" data-placement="bottom" title="Last 5 results">Form</th>
              <th class="correct-bets-header">Correct Outcomes</th>
              <th>Score</th>
            </tr>
          </thead>
        </table>
        {% else %}
        <table id="team_{{ team.id }}_leaderboard" class="display" style="width:100%">
          <thead>
            <tr>
              <th class="all"></th>
              <th>User</th>
              <th>Name</th>
            </tr>
          </thead>
        </table>
        {% endif %}
      </div>
    </div>
  </div>
  {% empty %}
  <div class="card border-light shadow mb-4">
    <div class="card-body">
      <h5>No teams yet, watch this space...</h5>
    </div>
  </div>
  {% endfor %}

</div>

<script type="text/javascript" src="{% static 'enter/overall_leaderboard.js' %}"></script>

<script>
  $(document).ready(function () {
    $("body").tooltip({
      selector: '[data-toggle=tooltip]',
      delay: {
        show: 500,
        hide: 0
    }
    });
  });
</script>

<script>
  $(document).ready(function () {
    $('#exploreDropdown').addClass('active');
  });
</script>

{% endblock content %}

gamesite/enter/templates/enter/results.html
{% extends "feed/base.html" %}
{% load static %}
{% load humanize %}

{% block content %}

{% include 'feed/profile_sidebar.html'%}

<div class="col-12 col-lg-9 mt-4">
<h2>Results</h2>

<div class="card border-light shadow mb-4">
  <div class="card-body">
    <div id="called_bets_table_container" data-url-called-bets-endpoint="{% url 'enter:called_bets_api' %}">
      <h3>Decided Outcomes</h3>
        <hr />
      <table id="called_bets_table" class="display" style="width:100%">
          <thead>
            <tr>
              <th></th>
              <th style="text-align: center;">Outcome</th>
              <th style="text-align: center;">Game Section</th>
              <th style="text-align: center;">Points</th>
              <th style="text-align: center;">Date</th>
            </tr>
          </thead>
        </table>
    </div>
  </div>
</div>

<div class="card border-light shadow mb-4">
  <div class="card-body">
      <h3>Game Progress</h3>
        <hr />
       <h5 class="mb-2 mt-3">Overall   <small class="text-muted">({{ game_progress.number_completed }} of {{ game_progress.total_number }})</small></h5>
      <div class="progress mb-3 mt-3">
        <div class="progress-bar" role="progressbar" style="width: {{ game_progress.percentage }}%" aria-valuenow="{{ game_progress.percentage }}" aria-valuemin="0" aria-valuemax="100">{{ game_progress.percentage }}%</div>
      </div>

      <h5 class="mb-2">Game Section Progress</h5>
      <p class="text-muted">The following progress bars show the percentage of bets that have been called in each section of the game.</p>

      {% for section in section_progress %}
      <h6>{{ section.title }}   <small class="text-muted">({{ section.number_completed }} of {{ section.total_number }})</small></h6>
      <div class="progress mb-3 mt-1">
        <div class="progress-bar bg-info" role="progressbar" style="width: {{ section.percentage }}%" aria-valuenow="{{ game_progress }}" aria-valuemin="0" aria-valuemax="100">{{ section.percentage }}%</div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>

<script type="text/javascript" src="{% static 'enter/called_bets_table.js' %}"></script>

<script>
  $(document).ready(function () {
    $('#exploreDropdown').addClass('active');
  });
</script>

{% endblock content %}